/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compie;
import bst.BST_draw;
import bst.BST_math;
import bst.BstMathComponent;
import bst.DisplaySimpleTree;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
/**
 *
 * @author clases
 */
public class Sintactico extends javax.swing.JFrame {

    /**
     * Creates new form Sintactico
     */
    public Sintactico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas las palabras" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Palabras simples" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Palabras compuestas" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Variables declaradas" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expr. matematicas" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comentarios" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Errores sintacticos" }));

        jButton1.setText("Generar Arbol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String anaa = (String) jComboBox5.getItemAt(1);
        BstMathComponent ecuacion = new BstMathComponent(anaa);
        BST_draw ventana_arbol = new BST_draw(ecuacion);
        ventana_arbol.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
       // if(evt.getStateChange()== getSelectedItem( )
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintactico().setVisible(true);
            }
        });
    }
    void execute(String txt)
    {
        this.setVisible(true);
              
        //declarar arreglos contenedores
        int all=1000;
        int sum[][]=new int[6][all];
        String todo[][]=new String[6][all];
        int lens[]=new int[6];
        String tipo[]={"simple","compuesta"};
        JComboBox combo[]={jComboBox1,jComboBox2,jComboBox3,jComboBox4,jComboBox5,jComboBox6};
        String error_str[]=new String[all];
        int errores[]=new int[all];
        int tot_errores=0;
        
        //mostrar string sin espacios
        txt=txt.replaceAll("\\s"," ");
        txt=txt.replaceAll("  "," ");
        String[] palabras = txt.split(" "); 
        txt=txt.toLowerCase();
        jTextArea1.setText(txt+"\n\n");
        int cant=txt.length();
        
        
        for(int a=0;a<palabras.length;a+=1)
        {
            palabras[a]=palabras[a].replaceAll("\\s","");
            if(palabras[a].length()>0){
            jComboBox1.addItem(palabras[a]);
            }
        }
            
        for(int d=0;d<2;d+=1)
        {
            //leer 
           Lexico lla = new Lexico();
           String Gur = lla.queryS("nom_pb","palabras","where tipo_pb='"+tipo[d]+"'","compie");
           String separado[]=Gur.split(" ");
            for(int a=0;a<palabras.length;a+=1)
            {   
                boolean encontro=false;
                for(int c=0;c<separado.length;c+=1)
                {
                    separado[c]=separado[c].replaceAll("\\s","");
                    if (palabras[a].equals(separado[c]))
                    {encontro=true;break;}
                }
                if (encontro)
                {
                    if(palabras[a].length()>0){
                    combo[d+1].addItem(palabras[a]+"");}
                }
            }
        }
        
        //
        boolean vr=false;
        boolean co=false;
        String suma="";
        String comen="";
        reiniciar();
        for(int p=0;p<palabras.length;p++)
        {
            if(palabras[p].equals("declarar"))
            {
                guardar_noerror(palabras[p]);
                if (p<palabras.length-1)
                {                    
                    jComboBox4.addItem(palabras[p+1]+"");
                    guardar_noerror(palabras[p+1]);
                }
            }
            
            if (!vr)
            {
                if(palabras[p].equals("mmatini"))
                {
                    vr=true;
                    suma="";
                    guardar_noerror(palabras[p]);
                }
            }
            else
            {
                if(!palabras[p].equals("mmattfin"))
                {suma+=palabras[p];guardar_noerror(palabras[p]);}
                else
                {
                    vr=false;
                    jComboBox5.addItem(suma);
                    guardar_noerror(palabras[p]);
                }
                
            }
            if (!co)
            {
                if(palabras[p].equals("/*"))
                {
                    co=true;
                    comen="";
                    guardar_noerror(palabras[p]);
                }
            }
            else
            {
                if(!palabras[p].equals("*\\"))
                {comen+=palabras[p];guardar_noerror(palabras[p]);}
                else
                {
                    co=false;
                    jComboBox6.addItem(comen);
                    guardar_noerror(palabras[p]);
                }
            }
        }
        //descartar errores
        for(int pal=0;pal<palabras.length;pal++)
        {
            boolean es_error=true;
            System.out.println("analizar: "+palabras[pal]);
            for(int ne=0;ne<obtener_nerror();ne++)
            {
                if (obtener_noerror(ne).equals(palabras[pal]))
                {
                    es_error=false;
                    System.out.println(obtener_noerror(ne)+" = "+palabras[pal]);
                }
            }
            if (es_error)
            {
                System.out.println(palabras[pal]+" es error.");
                if(palabras[pal].length()>0){
                jComboBox7.addItem(palabras[pal]);
                }
            }
        }
    }
    
    private int nerr=0;
    private String noerr[]=new String[100];
   public void reiniciar()
   {
       int nerr=0;
   }
   public void guardar_noerror(String noerror)
   {
       System.out.println(noerror+" no es un error;");
       noerr[nerr]=noerror;
       nerr++;
   }
   public int obtener_nerror()
   {
       return nerr;
   }
   public String obtener_noerror(int n)
   {
       return noerr[n];
   }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
